### ISSUE TITLE
Misannotations in Swedish-Talbanken

### ISSUE THREAD

**Issue by AleksandrsBerdicevskis** [UniversalDependencies/UD_Swedish-Talbanken#8]
There are four cases when "då" 'then' has UPOS = SCONJ and XPOS = AB ('adverb'). In all of them, UPOS should be "ADV".

**Comment by jnivre** [comment]
@gregarshinov First of all, sorry for the extremely slow response!

Regarding sent_id = sv-ud-test-188: The lemmatization in Swedish Talbanken has been performed automatically, and we have not been able to manually validate everything yet. When it comes to "sammansatt", it is the past participle of a particle verb that in the infinitive may be realized either as "sammansätta" (as a so-called fixed compound) or as "sätta samman" (as a so-called loose compound). The standard in the dictionary underlying the lemmatiser is to use the loose compound as the lemma for all forms of such particle verbs. Hence, "sätta_samman" is the correct lemma for "sammansatt". However, the lemmatiser is not perfect, so I have noticed that the form "sammansatta" (the plural form corresponding to "sammansatt") is lemmatised to "sammansatt", which is inconsistent. When we have time to do a full manual validation, such inconsistencies should of course be fixed.

Regarding sent_id = sv-ud-test-262: The word "första" (first) is not lemmatised as the article "en" ("a(n)"), but as the numeral "en" ("one"). Since these are homographs, there should probably be some way of distinguishing the lemmas, but the lemmatiser does not do this. The tag ADJ and the deprel amod is correct for ordinal numbers according to the guidelines. (Only cardinal numbers get NUM and nummod.)

I hope this clarifies the situation. Apologies again for the lateness of the reply.

**Comment by jnivre** [comment]
All of the problems reported on this page have now been fixed, except the lemmatisation of adverbs ending in -t, where there is no consensus yet (and a change would require extensive manual work).

**Comment by rueter** [comment]
@jnivre @LarsAhrenberg 
> Regarding sent_id = sv-ud-test-262: The word "första" (first) is not lemmatised as the article "en" ("a(n)"), but as the numeral "en" ("one"). Since these are homographs, there should probably be some way of distinguishing the lemmas, but the lemmatiser does not do this. The tag ADJ and the deprel amod is correct for ordinal numbers according to the guidelines. (Only cardinal numbers get NUM and nummod.)
> 

This caught my eye as an instance where the neutral cardinal form "ett" might provide the desired distinction, since counting without heads goes: "ett, två, tre..." Just a suggestion, I understand the amount of manual work involved.

**Comment by jnivre** [comment]
@rueter Thanks! The only problem is that we are using an external lemmatiser based on the SALDO lexicon, and we want to stay compatible with that if possible.

**Comment by AleksandrsBerdicevskis** [comment]
@jnivre @LarsAhrenberg I started creating an issue about the lemmatization of adverbials and then remembered that we have already had this discussion here. See also [here](https://github.com/SwedishJewellery/discussions/issues/1). As far as I know, none of the harmonization steps that we discussed have happened :)

Even though there is currently no consistent policy for Swedish, I have to decide what I do with Eukalyptus (where all adjectival adverbials are ADJs and have adjectival lemmas). For now, I will do what seems to require least effort: change the UPOS to ADV where necessary, but keep the lemma. This is more or less what currently happens in Talbanken (with some discrepancies: adverbial _särskilt_, for instance, always gets the lemma _särskilt_), but not in LinES.
